#!/usr/bin/env python3

import os

lexer = ""
with open('rat19f/lexer.py', 'r') as f:
    lexer_content = f.read()


program_start = """
'''Start of Program'''

def main():
    import sys
    filename = sys.argv[-1]
    lexer = Lexer(filename)
    with open('lexer.out', 'w') as f:
        f.write('{0:15}  {1}'.format('Tokens', 'Lexemes') + '\\n' + '-'*24 + '\\n')
        print('{0:15}  {1}'.format('Tokens', 'Lexemes') + '\\n' + '-'*24)
        for lexemes in lexer.scanner():
            if lexemes:
                f.write('{0:15}  {1}'.format(lexemes[0], lexemes[1]) + '\\n')
                print('{0:15}  {1}'.format(lexemes[0], lexemes[1]))
if __name__ == '__main__':
    main()
"""


with open('rat', 'w') as f:
        f.write('#!/usr/bin/env python3\n')
        f.write(lexer_content)
        f.write(program_start)

os.system('chmod +x rat')
